services:
  node:
    image: node:16
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: bash -c "yarn install && yarn dev"
